-- V1: users テーブルの作成（PostgreSQL 方言）
-- H2/MySQL の AUTO_INCREMENT ではなく PostgreSQL の IDENTITY 列を使う（sec05 type14 の方言差の実演）。
CREATE TABLE users (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
